dist: xenial
sudo: false
language: python
cache: pip
matrix:
  include:
    - python: 2.7
      env: TOXENV=py27
    - python: 3.6
      env: TOXENV=py36
    - env: TOXENV=flake8
install:
  - pip install tox
script:
  - tox
